const lessons=[
 {icon:'☀',title:{en:'Introduction to TOPCon Technology',hi:'TOPCon तकनीक का परिचय',gu:'TOPCon ટેકનોલોજીનો પરિચય'},body:{en:'<h2>What is TOPCon?</h2><p>Tunnel Oxide Passivated Contact is a high-efficiency N-type solar-cell technology. A thin tunnel-oxide layer and doped polysilicon contact reduce recombination losses.</p><div class="key-points"><span>Higher conversion efficiency</span><span>Lower degradation</span><span>Better temperature coefficient</span></div>',hi:'<h2>TOPCon क्या है?</h2><p>टनल ऑक्साइड पैसिवेटेड कॉन्टैक्ट उच्च दक्षता वाली N-टाइप सोलर सेल तकनीक है।</p><div class="key-points"><span>उच्च दक्षता</span><span>कम गिरावट</span><span>बेहतर तापमान प्रदर्शन</span></div>',gu:'<h2>TOPCon શું છે?</h2><p>ટનલ ઓક્સાઇડ પેસિવેટેડ કોન્ટેક્ટ ઉચ્ચ કાર્યક્ષમતા ધરાવતી N-ટાઇપ સોલર સેલ ટેકનોલોજી છે.</p><div class="key-points"><span>વધુ કાર્યક્ષમતા</span><span>ઓછું ડિગ્રેડેશન</span><span>સારું તાપમાન પ્રદર્શન</span></div>'}},
 {icon:'▦',title:{en:'Cell Loading & Stringing',hi:'सेल लोडिंग और स्ट्रिंगिंग',gu:'સેલ લોડિંગ અને સ્ટ્રિંગિંગ'},body:{en:'<h2>Cell preparation and stringing</h2><p>Verify cell type, power bin, colour and orientation before loading. Maintain ribbon alignment, soldering temperature, peel strength and cell-gap controls.</p><div class="key-points"><span>Correct cell orientation</span><span>Stable soldering profile</span><span>Zero micro-crack handling</span></div>',hi:'<h2>सेल तैयारी और स्ट्रिंगिंग</h2><p>लोडिंग से पहले सेल प्रकार, पावर बिन, रंग और दिशा की जाँच करें।</p>',gu:'<h2>સેલ તૈયારી અને સ્ટ્રિંગિંગ</h2><p>લોડિંગ પહેલાં સેલ પ્રકાર, પાવર બિન, રંગ અને દિશા ચકાસો.</p>'}},
 {icon:'⇄',title:{en:'Layup & Material Control',hi:'लेअप और सामग्री नियंत्रण',gu:'લેઅપ અને મટિરિયલ કંટ્રોલ'},body:{en:'<h2>Accurate module layup</h2><p>Control glass cleanliness, EVA/POE orientation, string positioning, bussing, barcode traceability and backsheet or rear-glass alignment.</p>',hi:'<h2>सटीक मॉड्यूल लेअप</h2><p>ग्लास सफाई, EVA/POE दिशा, स्ट्रिंग पोजिशन और ट्रेसबिलिटी नियंत्रित करें।</p>',gu:'<h2>ચોક્કસ મોડ્યુલ લેઅપ</h2><p>ગ્લાસ સફાઈ, EVA/POE દિશા, સ્ટ્રિંગ પોઝિશન અને ટ્રેસેબિલિટી નિયંત્રિત કરો.</p>'}},
 {icon:'▰',title:{en:'Lamination Process',hi:'लैमिनेशन प्रक्रिया',gu:'લેમિનેશન પ્રક્રિયા'},body:{en:'<h2>Lamination critical controls</h2><p>Verify recipe, vacuum pressure, heating uniformity, cycle time and cooling. Wrong settings can create bubbles, delamination, cell shift or broken cells.</p>',hi:'<h2>लैमिनेशन के महत्वपूर्ण नियंत्रण</h2><p>रेसिपी, वैक्यूम प्रेशर, तापमान, साइकिल टाइम और कूलिंग जाँचें।</p>',gu:'<h2>લેમિનેશનના મહત્વના નિયંત્રણો</h2><p>રેસિપી, વેક્યૂમ પ્રેશર, તાપમાન, સાયકલ ટાઇમ અને કૂલિંગ ચકાસો.</p>'}},
 {icon:'◎',title:{en:'EL & Visual Inspection',hi:'EL और दृश्य निरीक्षण',gu:'EL અને વિઝ્યુઅલ ઇન્સ્પેક્શન'},body:{en:'<h2>Defect detection</h2><p>Use EL to identify cracks, inactive areas, soldering defects and mismatch. Visual inspection confirms bubbles, foreign material, alignment and cosmetic defects.</p>',hi:'<h2>दोष पहचान</h2><p>क्रैक, इनएक्टिव एरिया, सोल्डरिंग दोष और मिसमैच के लिए EL का उपयोग करें।</p>',gu:'<h2>ખામીની ઓળખ</h2><p>ક્રેક, ઇનએક્ટિવ વિસ્તાર, સોલ્ડરિંગ ખામી અને મિસમેચ માટે EL નો ઉપયોગ કરો.</p>'}},
 {icon:'✓',title:{en:'Final Testing & Quality',hi:'अंतिम परीक्षण और गुणवत्ता',gu:'અંતિમ પરીક્ષણ અને ગુણવત્તા'},body:{en:'<h2>Final verification</h2><p>Complete sun-simulator, Hi-Pot, grounding, insulation and final visual tests. Grade the module only against approved specifications and maintain barcode traceability.</p>',hi:'<h2>अंतिम सत्यापन</h2><p>सन सिम्युलेटर, हाई-पॉट, ग्राउंडिंग, इंसुलेशन और अंतिम विजुअल टेस्ट पूरे करें।</p>',gu:'<h2>અંતિમ ચકાસણી</h2><p>સન સિમ્યુલેટર, હાઇ-પોટ, ગ્રાઉન્ડિંગ, ઇન્સ્યુલેશન અને અંતિમ વિઝ્યુઅલ ટેસ્ટ પૂર્ણ કરો.</p>'}}
];
const quiz=[
 {q:'What does TOPCon stand for?',a:['Tunnel Oxide Passivated Contact','Thermal Oxide Power Connection','Top Contact Network'],correct:0},
 {q:'Which parameter is critical during lamination?',a:['Vacuum pressure and temperature','Logo colour','Packing label size'],correct:0},
 {q:'Which test detects micro-cracks?',a:['EL inspection','Barcode scan','Frame measurement'],correct:0},
 {q:'Why is barcode traceability required?',a:['To track materials and process history','To increase module wattage','To reduce glass thickness'],correct:0},
 {q:'Which test verifies electrical insulation?',a:['Hi-Pot test','Visual inspection','Peel test'],correct:0}
];
let current=0,lang='en';const completed=new Set(JSON.parse(localStorage.getItem('topconCompleted')||'[]'));
function save(){localStorage.setItem('topconCompleted',JSON.stringify([...completed]));}
function renderList(){document.querySelector('#lessonList').innerHTML=lessons.map((l,i)=>`<button class="${i===current?'active':''} ${completed.has(i)?'done':''}" onclick="openLesson(${i})"><span>${i+1}. ${l.title[lang]}</span></button>`).join('');document.querySelector('#completedCount').textContent=completed.size;document.querySelector('#courseProgressBar').style.width=(completed.size/lessons.length*100)+'%';}
function openLesson(i){current=i;document.querySelector('#lessonView').classList.remove('hidden');document.querySelector('#quizView').classList.add('hidden');document.querySelector('#lessonTitle').textContent=lessons[i].title[lang];document.querySelector('#breadcrumb').textContent=`COURSE / LESSON ${i+1}`;document.querySelector('#lessonIcon').textContent=lessons[i].icon;document.querySelector('#lessonContent').innerHTML=lessons[i].body[lang]||lessons[i].body.en;document.querySelector('#prevLesson').disabled=i===0;document.querySelector('#nextLesson').textContent=i===lessons.length-1?'Take Assessment →':'Next Lesson →';document.querySelector('#completeLesson').textContent=completed.has(i)?'Completed ✓':'Mark Complete ✓';renderList();}
document.querySelector('#prevLesson').onclick=()=>openLesson(Math.max(0,current-1));document.querySelector('#nextLesson').onclick=()=>current===lessons.length-1?showQuiz():openLesson(current+1);document.querySelector('#completeLesson').onclick=()=>{completed.add(current);save();openLesson(current)};document.querySelector('#languageSelect').onchange=e=>{lang=e.target.value;openLesson(current)};document.querySelector('#playButton').onclick=()=>alert('Connect your MP4/video URL here. The interactive lesson text is active.');document.querySelector('#quizLink').onclick=showQuiz;
function showQuiz(){document.querySelector('#lessonView').classList.add('hidden');document.querySelector('#quizView').classList.remove('hidden');document.querySelector('#quizForm').innerHTML=quiz.map((x,i)=>`<div class="question"><b>${i+1}. ${x.q}</b>${x.a.map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join('')}</div>`).join('');}
document.querySelector('#submitQuiz').onclick=()=>{let correct=0;quiz.forEach((x,i)=>{const selected=document.querySelector(`input[name=q${i}]:checked`);if(selected&&Number(selected.value)===x.correct)correct++});const score=Math.round(correct/quiz.length*100),passed=score>=70,id='EV-'+new Date().getFullYear()+'-'+Math.random().toString(36).slice(2,8).toUpperCase(),date=new Date().toLocaleDateString('en-IN');localStorage.setItem('topconResult',JSON.stringify({score,passed,id,date}));document.querySelector('#quizResult').innerHTML=`<div class="result ${passed?'pass':'fail'}"><h2>${passed?'Congratulations!':'Please try again'}</h2><p>Your score: <b>${score}%</b></p>${passed?'<a href="certificate.html">Download Certificate</a>':'<p>Review the lessons and score at least 70%.</p>'}</div>`;if(passed){lessons.forEach((_,i)=>completed.add(i));save();renderList()}};
openLesson(0);if(location.hash==='#assessment')showQuiz();
